### ISSUE TITLE
Crash in Blender 2.93

### ISSUE THREAD

**Issue by LorenzWieseke** [JacquesLucke/blender_vscode#104] opened 2021-07-12 08:36 UTC
On a fresh install, it seems to work but as soon as I work a little with Blender 2.93, your extension gives me an error and I can't Build and Run the Add-on. Blender 2.92 works like a charm.

```
Traceback (most recent call last):
  File "c:\Users\wiese\.vscode\extensions\jacqueslucke.blender-development-0.0.16\pythonFiles\launch.py", line 14, in <module>
    blender_vscode.startup(
  File "c:\Users\wiese\.vscode\extensions\jacqueslucke.blender-development-0.0.16\pythonFiles\include\blender_vscode\__init__.py", line 17, in startup   
    communication.setup(editor_address, path_mappings)
  File "c:\Users\wiese\.vscode\extensions\jacqueslucke.blender-development-0.0.16\pythonFiles\include\blender_vscode\communication.py", line 21, in setup
    DEBUGPY_PORT = start_debug_server()
  File "c:\Users\wiese\.vscode\extensions\jacqueslucke.blender-development-0.0.16\pythonFiles\include\blender_vscode\communication.py", line 53, in start_debug_server
    debugpy.listen(("localhost", port))
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\debugpy\__init__.py", line 111, in listen
    from debugpy.server import api
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\debugpy\server\__init__.py", line 9, in <module>
    import debugpy._vendored.force_pydevd  # noqa
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\debugpy\_vendored\force_pydevd.py", line 45, in <module>
    preimport('pydevd', [
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\debugpy\_vendored\__init__.py", line 128, in preimport
    import_module(name)
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\debugpy\_vendored\pydevd\pydevd_plugins\__init__.py", line 5, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pkg_resources\__init__.py", line 3257, in <module>
    def _initialize_master_working_set():
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pkg_resources\__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pkg_resources\__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pkg_resources\__init__.py", line 573, in _build_master
    ws = cls()
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pkg_resources\__init__.py", line 566, in __init__
    self.add_entry(entry)
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\pkg_resources\__init__.py", line 620, in add_entry
    self.entry_keys.setdefault(entry, [])
TypeError: unhashable type: 'list'
Saved session recovery to 'C:\Users\wiese\AppData\Local\Temp\quit.blend'
Exception in module unregister(): 'C:\\Users\\wiese\\AppData\\Roaming\\Blender Foundation\\Blender\\2.93\\scripts\\addons\\GLBTextureTools\\__init__.py'
Traceback (most recent call last):
  File "c:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 438, in disable
    mod.unregister()
  File "C:\Users\wiese\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\GLBTextureTools\__init__.py", line 43, in unregister
    auto_load.unregister()
  File "C:\Users\wiese\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\GLBTextureTools\auto_load.py", line 41, in unregister
    bpy.utils.unregister_class(cls)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
```

**Comment by LorenzWieseke** [comment] 2021-07-30 09:50
So to prevent blender from crashing I deleted all addons, then separately adding each add-on, and figured out It crashed once I added Xatlas.

Still the auto_loader gives me an error once I run two separate addons, both using the auto loader.

**Comment by HugoMcPhee** [comment] 2022-08-16 15:53
I got the same issue with xatlas enabled, 
to fix, I edited the xatlas `__init__.py` file, to convert `__path__` to a non-list

```
# make sure path's not a list here
edited_path = __path__
if type(edited_path) == list:
    edited_path = edited_path[0]

sys.path.append(edited_path)
```

**Comment by Mateusz-Grzelinski** [comment] 2024-08-01 20:04
@LorenzWieseke I will close the issue as it looks like problem with xatlas. If you want please provide a way to reproduce the issue adn reopen.

**Closed by Mateusz-Grzelinski** 2024-08-01 20:04 UTC
