### ISSUE TITLE
Blender: Start creates copy of add-on when running in Blender 4.2

### ISSUE THREAD

**Issue by Dangry98** [JacquesLucke/blender_vscode#168] opened 2024-07-17 22:14 UTC
Running Blender:Start will make a copy of the add-on, meaning two add-on are run at the same time. The orginal addon is inside blender_org, a copy will be added to user_default. If the add-on is in the user_default from the start Blender crashes, so its seems it only works in blender_org, but then a copy is created.

![image](https://github.com/user-attachments/assets/7c446342-5dec-46aa-8462-d0f45e84c068)
![image](https://github.com/user-attachments/assets/2804e812-d5ba-433e-b29f-5e5b630e3258)

**Comment by Mateusz-Grzelinski** [comment] 2024-07-22 08:21
Hi just a quick reply: where are you doing your add-on development? If I remember correctly this extension will do a hard link (in windows links are a bit weird) of your add-on to blender directory for add-ons. 
So if you are developing your add-on in blender add-on folder, this extension might create a duplicate but I would need to check deeper.

**Comment by Dangry98** [comment] 2024-07-22 17:40
@Mateusz-Grzelinski Hi, I am working in the blender_org folder, if I try to do it in user_default and the start up Blender with VS Code it just crashes on all of the add-on I tried to far.

**Comment by Mateusz-Grzelinski** [comment] 2024-07-22 19:10
your duplicate addon might be coming from 

- `Scripts Directories` user setting https://docs.blender.org/manual/en/latest/advanced/extensions/addons.html#user-defined-add-on-path
- you are working in directory that is already loaded to blender by default https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html#blender-directory-path-layout

When if you start bledner from VS code VS code will make sure that blender can see the addon by making a hard link to `scripts/addons/<addon name>`.
When you can see the duplicate of addon, what is the path reported? 
![image](https://github.com/user-attachments/assets/afe31797-04ed-4a40-a2ce-e35f52178f6e)

**Comment by Dangry98** [comment] 2024-07-22 19:13
Here is the path:
![image](https://github.com/user-attachments/assets/51e5ad2f-2123-4825-b563-86294496817b)

**Comment by Dangry98** [comment] 2024-07-22 19:15
> your duplicate addon might be coming from
> 
> Scripts Directories user setting https://docs.blender.org/manual/en/latest/advanced/extensions/addons.html#user-defined-add-on-path
> you are working in directory that is already loaded to blender by default https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html#blender-directory-path-layout

I have never used them to load any add-ons, so thats probely not the problem

**Comment by Mateusz-Grzelinski** [comment] 2024-07-22 19:16
oh, I am not used to new extension system, i just found the path you are talking about. This is the second case that I was talking about. You are working in directory that is already loaded to blender by default.
No, you need to have your addon outside of blender managed directory (however is is called).
For example I have it like this: 
![image](https://github.com/user-attachments/assets/0263b39c-d1fd-46a0-b3d6-a5fccd478524)

**Comment by Mateusz-Grzelinski** [comment] 2024-07-22 19:18
if you are using `addon` the VS code will setup your addon in `scripts/addons` and if you are using new `extension` you addon will be setup in `user_default`

**Comment by Dangry98** [comment] 2024-07-22 19:28
Oh! Thank you so much! It seems to be working! I did not know that it was possible to run from an external folder! Thats so nice!

The only problem I see with this metod is that it's slightly less convenient since I usually work and do iterations quite often, and then send over my Blender config folder to another computer. Then it's quite nice if the add-on is placed directly in the Blender config files to begin with. But thats a nit pick. Anyway, thanks for the help! I appreciate it!

**Comment by Mateusz-Grzelinski** [comment] 2024-07-22 21:13
on linux I would recommend to copy with option to follow the links. But maybe we can also fix it in code. Will see. Made a draft with fix.

**Comment by Dangry98** [comment] 2024-07-22 21:16
Awsome! Thank you so much!

**Comment by Mateusz-Grzelinski** [comment] 2024-07-26 19:07
Completed by mistake. It is worked on in #172

**Closed** 2024-08-17 14:47 UTC
Labels: bug

**Comment by Mateusz-Grzelinski** [comment] 2024-08-17 15:53
No idea. I mean if we ask Jack nicely he will release it for us relatively quickly, the bigger issue is how many bugs did I introduce... :)
Because I have been working a lot on this repo I have set for myself this non formal milestone for next release. https://github.com/JacquesLucke/blender_vscode/milestone/1

**Comment by Dangry98** [comment] 2024-08-17 15:55
> No idea. I mean if we ask Jack nicely he will release it for us relatively quickly, the bigger issue is how many bugs did I introduce... :) Because I have been working a lot on this repo I have set for myself this non formal milestone for next release. https://github.com/JacquesLucke/blender_vscode/milestone/1

Alright then, thanks for the answere :)
