### ISSUE TITLE
Blender 4.0 and Run Script Error from VSCode

### ISSUE THREAD

**Issue by ericwomer** [JacquesLucke/blender_vscode#151] opened 2023-11-05 02:53 UTC
Blender 4.0 23e3f8f563960655ae084cbffa7defbe34f29451
Ubuntu 23.04
Python 3.10 (bundled with Blender)

After starting blender and attempting to run the script from vscode I get the following error.

```Traceback (most recent call last):
  File "/home/eric/.vscode/extensions/jacqueslucke.blender-development-0.0.18/pythonFiles/include/blender_vscode/utils.py", line 22, in always
    try: func()
  File "/home/eric/.vscode/extensions/jacqueslucke.blender-development-0.0.18/pythonFiles/include/blender_vscode/operators/script_runner.py", line 24, in run_script_action
    bpy.ops.dev.run_script(context, filepath=path)
  File "/home/eric/.local/share/Blender/blender-4.0/4.0/scripts/modules/bpy/ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "/home/eric/.local/share/Blender/blender-4.0/4.0/scripts/modules/bpy/ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported```

The script confirms to run from the blender script editor

the script (its actually any script or addon) is as follows.

```
import bpy

bpy.ops.mesh.primitive_cube_add(size=4)

cube_obj = bpy.context.active_object

cube_obj.location.z = 5
```

**Comment by Andrej730** [comment] 2023-11-05 05:33
the old context override method `bpy.ops.dev.run_script(context, filepath=path)` is not supported anymore since Blender 4.0, it needs to be
```python
with bpy.context.temp_override(**context):
	bpy.ops.dev.run_script(filepath=path)
```

But be careful since there is an issue with new temp override where you cannot longer use areas from other screens in override or it will produce [Area not found in screen](https://projects.blender.org/blender/blender/issues/108763) (reported it to Blender)

**Comment by monnerHenster** [comment] 2023-11-18 15:03
> the old context override method `bpy.ops.dev.run_script(context, filepath=path)` is not supported anymore since Blender 4.0, it needs to be
> 
> ```python
> with bpy.context.temp_override(**context):
> 	bpy.ops.dev.run_script(filepath=path)
> ```
> 
> But be careful since there is an issue with new temp override where you cannot longer use areas from other screens in override or it will produce [Area not found in screen](https://projects.blender.org/blender/blender/issues/108763) (reported it to Blender)

After modifying it according to your description, the script is running successfully, thanks!

**Comment by Ladvien** [comment] 2023-12-29 21:00
Hello @ericwomer and @monnerHenster,

It seems this may be fixed in the latest push, could you confirm?

https://github.com/JacquesLucke/blender_vscode/commit/55fe6bb89bcdf14bedf25b89f2176848c386e534

**Comment by BadDogSkyrim** [comment] 2023-12-30 12:06
I can confirm that the latest push fixed the problem for me.

**Comment by CGArtPython** [comment] 2024-01-02 06:57
Thank you @Ladvien for pointing out the fix!
Thank you @BadDogSkyrim for confirming! 

version [0.0.19](https://marketplace.visualstudio.com/items/JacquesLucke.blender-development/changelog) of the extension from 2023-12-05 should have this fix

**Closed by CGArtPython** 2024-01-02 06:57 UTC
