### ISSUE TITLE
Unable to import 'bpy' pylint(import-error)

### ISSUE THREAD

**Issue by IamKraZ** [JacquesLucke/blender_vscode#51] opened 2019-10-01 02:57 UTC
Hello, 
I get the error "Unable to import 'bpy' pylint(import-error) [1,1] for anything blender.

Note I'm running Blender 2.80.75, VSCode version 1.38.1, Python 3.7.4 64bit, on a Windows 10 OS, and the latest extensions for Blender Development and Linting, debugging (which Blender Development addon needs).

It also errors on any Blender code.

Any help would be greatly appreciated :)

VSCode pic enclosed.

<img width="960" alt="BlendDevVSCode" src="https://user-images.githubusercontent.com/31492582/65930938-452eb300-e3cd-11e9-9606-b650802f38c5.png">

**Comment by JacquesLucke** [comment] 2019-10-12 17:24
This extension does not deal with autocompletion and linting so far.

You can either disable the linting or use a project like https://github.com/nutti/fake-bpy-module.

Closing because this is not a bug in this extension.

**Closed by JacquesLucke** 2019-10-12 17:24 UTC
