### ISSUE TITLE
Request : adding / list this extension to Open VSX org. 

### ISSUE THREAD

**Issue by lalamax3d** [JacquesLucke/blender_vscode#214] opened 2024-12-08 09:56 UTC
Hi,

this is an amazing extension, thanks for creating this.
now a days, lot of new editors are landing like Cursor n Windsurf to name a few. Later one supports (https://open-vsx.org/).
Just curious is it possible to list extension there.

Also i tried to save vsix file and install in windsurf, loads fine but running (starting blender) gives error.
![image](https://github.com/user-attachments/assets/178eeae7-1332-4607-a113-4a86f14ceb35)

Any ideas.. or hope..
thanks in advance.

**Comment by Mateusz-Grzelinski** [comment] 2024-12-08 17:33
Is it a duplicate of #157? 
I am not against, I am just not willing to spend time on it. 

The command registration mechanism changed in newer versions of VSCode, I think we are using older method: manually listing commands in https://github.com/JacquesLucke/blender_vscode/blob/master/package.json

**Closed** 2024-12-08 17:38 UTC
